services:
  - type: web
    name: hospital-management-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hospital-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: hospital-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: hospital-db
          property: password
      - key: FRONTEND_URL
        value: https://hospitals-management-system.vercel.app

databases:
  - name: hospital-db
    databaseName: hospital_db
    plan: free
